alias gst='git status '

# add alias for dotdrop
alias dotdrop='~/dotfiles/dotdrop.sh --cfg=~/dotfiles/config.yaml'

# Add bash aliases.
if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

