set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" other plugins
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'morhetz/gruvbox'



" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" plugin setup
colorscheme gruvbox
set background=dark

" nerdtree
"let NERDTreeMinimalUI = 1
let g:NERDTreeNodeDelimiter = "\u00a0"


" settings

set tabstop=4 " visual spaces per TAB
set softtabstop=4 " number of spaces in tab when edit
set number " show line numbers
set wildmenu " visual autocomplete for command menu
set showmatch " highlight matching [{(
set foldmethod=marker " folding method
set foldmarker={,} " folding between { and }

" mappings
nmap ö ddO
nmap <S-Enter> O<Esc>
nmap <CR> o<Esc>

nnoremap <silent> <Space> @=(foldlevel('.')?'za':"\<    Space>")<CR>

