config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
profiles:
  laptop:
    dotfiles:
    - f_tmux.conf
    - f_vimrc
    - f_bashrc
  work:
    dotfiles:
    - f_tmux.conf
    - f_vimrc
    - f_bashrc
